"""Adiciona data_hora em rl_tramitacoes

Revision ID: 1115a132af71
Revises: a3ed4e7e3514
Create Date: 2025-11-05 01:40:45.855216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1115a132af71'
down_revision = 'a3ed4e7e3514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rl_tramitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rl_tramitacoes', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###
