"""Criação inicial

Revision ID: e4d7ca7b70ef
Revises: 
Create Date: 2025-11-10 11:35:07.850529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d7ca7b70ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    # Garantir a criação dos schemas antes de criar qualquer tabela neles
    op.execute('CREATE SCHEMA IF NOT EXISTS camara')
    op.execute('CREATE SCHEMA IF NOT EXISTS usuarios')
    op.execute('CREATE SCHEMA IF NOT EXISTS senado')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tp_situacao',
    sa.Column('id_situacao', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ds_situacao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_situacao'),
    sa.UniqueConstraint('ds_situacao'),
    schema='camara'
    )
    op.create_table('tp_temas',
    sa.Column('id_tema', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ds_tema', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_tema'),
    sa.UniqueConstraint('ds_tema'),
    schema='camara'
    )
    op.create_table('tp_tramitacao',
    sa.Column('id_tramitacao', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ds_tramitacao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_tramitacao'),
    sa.UniqueConstraint('ds_tramitacao'),
    schema='camara'
    )
    op.create_table('tb_projeto',
    sa.Column('id_projeto', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('titulo_projeto', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ano_inicio', sa.String(length=4), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('sigla_orgao', sa.String(length=100), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('id_ultima_situacao', sa.Integer(), nullable=True),
    sa.Column('id_ultima_tramitacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ultima_situacao'], ['camara.tp_situacao.id_situacao'], ),
    sa.ForeignKeyConstraint(['id_ultima_tramitacao'], ['camara.tp_tramitacao.id_tramitacao'], ),
    sa.PrimaryKeyConstraint('id_projeto'),
    schema='camara'
    )
    op.create_table('rl_temas',
    sa.Column('id_rl_temas', sa.Integer(), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=True),
    sa.Column('id_tema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_projeto'], ['camara.tb_projeto.id_projeto'], ),
    sa.ForeignKeyConstraint(['id_tema'], ['camara.tp_temas.id_tema'], ),
    sa.PrimaryKeyConstraint('id_rl_temas'),
    schema='camara'
    )
    op.create_table('rl_tramitacoes',
    sa.Column('id_rl_tramitacao', sa.Integer(), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('id_tramitacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['camara.tb_projeto.id_projeto'], ),
    sa.ForeignKeyConstraint(['id_situacao'], ['camara.tp_situacao.id_situacao'], ),
    sa.ForeignKeyConstraint(['id_tramitacao'], ['camara.tp_tramitacao.id_tramitacao'], ),
    sa.PrimaryKeyConstraint('id_rl_tramitacao'),
    schema='camara'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rl_tramitacoes', schema='camara')
    op.drop_table('rl_temas', schema='camara')
    op.drop_table('tb_projeto', schema='camara')
    op.drop_table('tp_tramitacao', schema='camara')
    op.drop_table('tp_temas', schema='camara')
    op.drop_table('tp_situacao', schema='camara')
    # ### end Alembic commands ###
